# Generated by Django 5.1.6 on 2025-02-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_collaborator_project_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="collaborator",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="collaborator",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="collaborator",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner_id",
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="collaborator",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="unique_collaborator"
            ),
        ),
    ]
