# Generated by Django 5.1.6 on 2025-02-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_project_id_collaborator_project_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="description",
            new_name="code",
        ),
    ]
